version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: superpass
      POSTGRES_USER: superadmin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080